// src/constants/features.ts
// Runtime feature flags. Flip to enable/disable subsystems without touching
// call sites. Deliberately tiny and dependency-free.
//
// LOCAL_LLM_ENABLED:
//   Build B — LLM voice wrapper for medical reads.
//   HTP0 force removed; uses CPU fallback (n_gpu_layers: 0) so all devices
//   are safe. inferLocal wraps deterministic SQL results conversationally.
//   Medical numbers/dosages never generated by LLM — SQL is source of truth.
export const LOCAL_LLM_ENABLED = true;
